import React, { useEffect, useMemo, useState } from 'react';
import { api, toProfile } from './services/api';
import type { AccessibilitySettings, HealthRecord, Medication, MedicationLog, UserProfile, ActiveTab } from './types';
import { WhatsAppHeader } from './components/WhatsAppHeader';
import { WhatsAppTabBar } from './components/WhatsAppTabBar';
import { DailyDiaryView } from './components/DailyDiaryView';
import { MedicationsView } from './components/MedicationsView';
import { ChartsView } from './components/ChartsView';
import { ReportView } from './components/ReportView';
import { NewRecordModal } from './components/NewRecordModal';
import { StorageService } from './services/storage';

const defaultAccessibility: AccessibilitySettings = { fontSize: 'grande', highContrast: false, soundAlerts: true, voiceReadout: true };
function Login({ onAuthenticated }: { onAuthenticated: (u: UserProfile) => void }) { const [register, setRegister] = useState(false); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (e: React.FormEvent) => { e.preventDefault(); setError(''); setLoading(true); try { const result = register ? await api.register(name, email, password) : await api.login(email, password); onAuthenticated(toProfile(result.user)); } catch (err) { setError(err instanceof Error ? err.message : 'Não foi possível entrar.'); } finally { setLoading(false); } }; return <main className="min-h-screen whatsapp-bg flex items-center justify-center p-4"><form onSubmit={submit} className="bg-white w-full max-w-md rounded-3xl shadow-2xl p-7 border-4 border-[#075E54] space-y-4"><div className="text-center"><div className="text-5xl">🩺</div><h1 className="text-3xl font-black text-[#075E54]">GlicoPress</h1><p className="text-slate-600">Seu diário de saúde, com segurança.</p></div>{register && <input required value={name} onChange={e => setName(e.target.value)} placeholder="Seu nome" className="w-full border-2 rounded-xl p-3" />}<input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="E-mail" className="w-full border-2 rounded-xl p-3" /><input required minLength={8} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Senha (mínimo 8 caracteres)" className="w-full border-2 rounded-xl p-3" />{error && <p role="alert" className="text-red-700 bg-red-50 rounded-xl p-3 text-sm font-bold">{error}</p>}<button disabled={loading} className="w-full bg-[#25D366] text-slate-950 font-black py-3 rounded-xl disabled:opacity-50">{loading ? 'Aguarde...' : register ? 'Criar minha conta' : 'Entrar'}</button><button type="button" onClick={() => setRegister(!register)} className="w-full text-[#075E54] font-bold text-sm">{register ? 'Já tenho uma conta' : 'Criar nova conta'}</button><p className="text-xs text-slate-500 text-center">Seus dados clínicos são privados e só ficam disponíveis para sua conta.</p></form></main>; }

export default function App() { const [user, setUser] = useState<UserProfile | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [records, setRecords] = useState<HealthRecord[]>([]); const [medications, setMedications] = useState<Medication[]>([]); const [medicationLogs, setMedicationLogs] = useState<MedicationLog[]>([]); const [activeTab, setActiveTab] = useState<ActiveTab>('diario'); const [newOpen, setNewOpen] = useState(false); const [accessibility, setAccessibility] = useState<AccessibilitySettings>(() => { try { return StorageService.getAccessibilitySettings(); } catch { return defaultAccessibility; } });
  const loadData = async () => { setLoading(true); setError(''); try { const [r, m] = await Promise.all([api.records(), api.medications()]); setRecords(r); setMedications(m.medications); setMedicationLogs(m.logs); } catch (e) { setError(e instanceof Error ? e.message : 'Erro ao carregar seus dados.'); } finally { setLoading(false); } };
  useEffect(() => { api.me().then(x => setUser(toProfile(x.user))).catch(() => {}).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (user) { loadData(); const raw = localStorage.getItem('glicopress_records_v2'); if (raw && !sessionStorage.getItem(`migrated:${user.id}`)) api.migrateLocal(JSON.parse(raw)).then(() => sessionStorage.setItem(`migrated:${user.id}`, '1')).then(loadData).catch(() => {}); } }, [user]);
  const saveRecord = async (r: Omit<HealthRecord, 'id' | 'timestamp'>) => { if (!user) return; try { await api.createRecord({ ...r, id: '', timestamp: `${r.date}T${r.time || '12:00'}:00.000Z` }); setNewOpen(false); await loadData(); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível salvar o registro.'); } };
  const takeDose = async (m: Medication, time: string) => { try { await api.logMedication(m, time); await loadData(); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível registrar a tomada.'); } };
  const today = new Date().toISOString().slice(0, 10); const todayCount = useMemo(() => records.filter(r => r.date === today).length, [records, today]); const pending = useMemo(() => medications.filter(m => m.active).reduce((n, m) => n + m.times.filter(t => !medicationLogs.some(l => l.medicationId === m.id && l.date === today && l.scheduledTime === t)).length, 0), [medications, medicationLogs, today]);
  if (loading && !user) return <div className="min-h-screen flex items-center justify-center font-bold text-[#075E54]">Carregando...</div>; if (!user) return <Login onAuthenticated={setUser} />;
  return <div className={`${accessibility.fontSize === 'extra' ? 'text-lg' : accessibility.fontSize === 'grande' ? 'text-base' : 'text-sm'} min-h-screen flex flex-col`}>{error && <div role="alert" className="bg-red-100 text-red-800 p-2 text-center font-bold">{error}<button className="ml-3 underline" onClick={() => setError('')}>fechar</button></div>}<WhatsAppHeader user={user} accessibility={accessibility} onUpdateAccessibility={v => { setAccessibility(v); StorageService.saveAccessibilitySettings(v); }} onOpenUserModal={async () => { await api.logout(); setUser(null); }} /><WhatsAppTabBar activeTab={activeTab} onTabChange={setActiveTab} pendingMedCount={pending} todayRecordsCount={todayCount} /><main className="flex-1">{activeTab === 'diario' && <DailyDiaryView records={records} user={user} accessibility={accessibility} onOpenNewRecord={() => setNewOpen(true)} onDeleteRecord={async id => { await api.deleteRecord(id); await loadData(); }} onOpenMedicationsTab={() => setActiveTab('medicamentos')} />}{activeTab === 'medicamentos' && <MedicationsView medications={medications} medicationLogs={medicationLogs} user={user} accessibility={accessibility} onTakeDose={takeDose} onUndoDose={() => loadData()} onSaveMedication={async m => { await api.createMedication(m); await loadData(); }} onDeleteMedication={async id => { await api.deleteMedication(id); await loadData(); }} />}{activeTab === 'graficos' && <ChartsView records={records} user={user} accessibility={accessibility} />}{activeTab === 'relatorio' && <ReportView records={records} user={user} medications={medications} accessibility={accessibility} />}</main><NewRecordModal isOpen={newOpen} onClose={() => setNewOpen(false)} onSave={saveRecord} user={user} accessibility={accessibility} /></div>;
}
