import type { VercelRequest, VercelResponse } from '../server/vercel-types';
import { and, desc, eq, sql } from 'drizzle-orm';
import { db, schema } from '../server/db';
import { clearSession, getSessionUserId, hashPassword, json, method, normalizeEmail, safeError, setSession, verifyPassword } from '../server/auth';

const publicUser = (u: schema.User) => ({ id: u.id, name: u.name, email: u.email, createdAt: u.createdAt });
const pathOf = (req: VercelRequest) => (Array.isArray(req.query.path) ? req.query.path.join('/') : String(req.query.path ?? '')).replace(/^api\/?/, '');
const body = (req: VercelRequest) => (req.body && typeof req.body === 'object' ? req.body as Record<string, unknown> : {});
const requireUser = async (req: VercelRequest, res: VercelResponse) => { const id = await getSessionUserId(req); if (!id) { json(res, 401, { error: 'Sessão expirada. Faça login novamente.' }); return null; } return id; };
const validNumber = (x: unknown) => x === undefined || x === null || (typeof x === 'number' && Number.isFinite(x));

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Cache-Control', 'no-store');
  const p = pathOf(req); const input = body(req);
  try {
    if (p === 'auth/register' && method(req, ['POST'])) { const email = normalizeEmail(input.email); const name = typeof input.name === 'string' ? input.name.trim() : ''; const password = typeof input.password === 'string' ? input.password : ''; if (!name || !email.includes('@') || password.length < 8) return json(res, 400, { error: 'Informe nome, e-mail válido e senha com pelo menos 8 caracteres.' }); const exists = await db.select({ id: schema.users.id }).from(schema.users).where(eq(schema.users.email, email)).limit(1); if (exists.length) return json(res, 400, { error: 'Não foi possível criar a conta com esses dados.' }); const [u] = await db.insert(schema.users).values({ name, email, passwordHash: await hashPassword(password) }).returning(); await setSession(res, u.id); return json(res, 201, { user: publicUser(u) }); }
    if (p === 'auth/login' && method(req, ['POST'])) { const email = normalizeEmail(input.email); const password = typeof input.password === 'string' ? input.password : ''; const [u] = await db.select().from(schema.users).where(eq(schema.users.email, email)).limit(1); if (!u || !(await verifyPassword(password, u.passwordHash))) return json(res, 401, { error: 'E-mail ou senha inválidos.' }); await setSession(res, u.id); return json(res, 200, { user: publicUser(u) }); }
    if (p === 'auth/logout' && method(req, ['POST'])) { clearSession(res); return json(res, 200, { ok: true }); }
    const userId = await requireUser(req, res); if (!userId) return;
    if (p === 'auth/me' && method(req, ['GET'])) { const [u] = await db.select().from(schema.users).where(eq(schema.users.id, userId)).limit(1); return u ? json(res, 200, { user: publicUser(u) }) : json(res, 401, { error: 'Sessão expirada.' }); }
    if (p === 'records' && method(req, ['GET'])) { const limit = Math.min(Math.max(Number(req.query.limit ?? 200), 1), 500); const rows = await db.select().from(schema.dailyRecords).where(eq(schema.dailyRecords.userId, userId)).orderBy(desc(schema.dailyRecords.recordedAt)).limit(limit); return json(res, 200, { records: rows }); }
    if (p === 'records' && method(req, ['POST'])) { if (!validNumber(input.glucose) || !validNumber(input.systolicPressure) || !validNumber(input.diastolicPressure)) return json(res, 400, { error: 'Valores de saúde inválidos.' }); const [r] = await db.insert(schema.dailyRecords).values({ userId, recordedAt: new Date(String(input.recordedAt ?? new Date().toISOString())), glucose: input.glucose as number | null, glucoseContext: input.glucoseContext as string | null, systolicPressure: input.systolicPressure as number | null, diastolicPressure: input.diastolicPressure as number | null, heartRate: input.heartRate as number | null, weight: input.weight as number | null, symptoms: Array.isArray(input.symptoms) ? input.symptoms.join(', ') : null, notes: typeof input.notes === 'string' ? input.notes.slice(0, 2000) : null }).returning(); return json(res, 201, { record: r }); }
    const recordMatch = p.match(/^records\/([^/]+)$/); if (recordMatch) { const id = recordMatch[1]; if (req.method === 'DELETE') { await db.delete(schema.dailyRecords).where(and(eq(schema.dailyRecords.id, id), eq(schema.dailyRecords.userId, userId))); return json(res, 200, { ok: true }); } if (req.method === 'PUT') { const [r] = await db.update(schema.dailyRecords).set({ ...input, userId: undefined, updatedAt: new Date() } as never).where(and(eq(schema.dailyRecords.id, id), eq(schema.dailyRecords.userId, userId))).returning(); return r ? json(res, 200, { record: r }) : json(res, 404, { error: 'Registro não encontrado.' }); } }
    if (p === 'medications' && method(req, ['GET'])) { const meds = await db.select().from(schema.medications).where(eq(schema.medications.userId, userId)).orderBy(desc(schema.medications.createdAt)).limit(200); const logs = await db.select().from(schema.medicationLogs).where(eq(schema.medicationLogs.userId, userId)).orderBy(desc(schema.medicationLogs.takenAt)).limit(500); return json(res, 200, { medications: meds, logs }); }
    if (p === 'medications' && method(req, ['POST'])) { if (typeof input.name !== 'string' || !input.name.trim()) return json(res, 400, { error: 'Nome do medicamento é obrigatório.' }); const [m] = await db.insert(schema.medications).values({ userId, name: input.name.trim(), dosage: String(input.dosage ?? ''), schedule: Array.isArray(input.schedule) ? input.schedule.filter(x => typeof x === 'string') as string[] : [], notes: typeof input.notes === 'string' ? input.notes : null, active: input.active !== false }).returning(); return json(res, 201, { medication: m }); }
    const medMatch = p.match(/^medications\/([^/]+)$/); if (medMatch && req.method === 'DELETE') { await db.delete(schema.medications).where(and(eq(schema.medications.id, medMatch[1]), eq(schema.medications.userId, userId))); return json(res, 200, { ok: true }); }
    if (medMatch && req.method === 'PUT') { const values = { name: typeof input.name === 'string' ? input.name.trim() : undefined, dosage: typeof input.dosage === 'string' ? input.dosage : undefined, schedule: Array.isArray(input.schedule) ? input.schedule.filter(x => typeof x === 'string') as string[] : undefined, notes: typeof input.notes === 'string' ? input.notes : undefined, active: typeof input.active === 'boolean' ? input.active : undefined, updatedAt: new Date() }; const [m] = await db.update(schema.medications).set(values).where(and(eq(schema.medications.id, medMatch[1]), eq(schema.medications.userId, userId))).returning(); return m ? json(res, 200, { medication: m }) : json(res, 404, { error: 'Medicamento não encontrado.' }); }
    if (p === 'medication-logs' && method(req, ['POST'])) { const medId = String(input.medicationId); const [med] = await db.select({ id: schema.medications.id }).from(schema.medications).where(and(eq(schema.medications.id, medId), eq(schema.medications.userId, userId))).limit(1); if (!med) return json(res, 404, { error: 'Medicamento não encontrado.' }); const [l] = await db.insert(schema.medicationLogs).values({ medicationId: medId, userId, takenAt: new Date(String(input.takenAt ?? new Date().toISOString())), status: String(input.status ?? 'tomado'), notes: typeof input.notes === 'string' ? input.notes : null }).returning(); return json(res, 201, { log: l }); }
    if (p === 'migration/local' && method(req, ['POST'])) { const records = Array.isArray(input.records) ? input.records : []; let imported = 0; for (const x of records.slice(0, 500)) { const r = x as Record<string, unknown>; if (typeof r.timestamp !== 'string') continue; await db.insert(schema.dailyRecords).values({ userId, recordedAt: new Date(r.timestamp), glucose: typeof r.glucose === 'number' ? r.glucose : null, glucoseContext: typeof r.glucoseContext === 'string' ? r.glucoseContext : null, systolicPressure: typeof r.systolic === 'number' ? r.systolic : null, diastolicPressure: typeof r.diastolic === 'number' ? r.diastolic : null, heartRate: typeof r.pulse === 'number' ? r.pulse : null, symptoms: Array.isArray(r.symptoms) ? r.symptoms.join(', ') : null, notes: typeof r.notes === 'string' ? r.notes : null }).onConflictDoNothing(); imported++; } return json(res, 200, { imported }); }
    return json(res, 404, { error: 'Endpoint não encontrado.' });
  } catch (error) { return safeError(res, error); }
}
